
const schoolMockup = [
    {
        id: 1,
        title: "펀딩 진행중",
        imgURL: "./img/Mschoolphoto1.jpg",
        name: "김포 사랑유치원",
        funding: "0/20 명",
        FundingPeriod: "7월2일~7월22일",
        personnel: "20명",
        like: 10,
        price: 330000,
        price2: 660000,
        price3: 1550000, 
        optionTitle: "10회권",
        optionTitle02: "1달권",
        optionTitle03: "3개월권",
        detailURL1: "./img/school_img1.jpg",
        detailURL2: "./img/school_img2.jpg",
        detailURL3: "./img/school_img3.jpg",
        company: "주식회사 패밀리도그"
      },
      {
        id: 2,
        title: "펀딩 진행중",
        imgURL: "./img/Mschoolphoto2.jpg",
        name: "홍대 스타유치원",
        funding: "0/20 명",
        FundingPeriod: "7월10일~7월20일",
        personnel: "20명",
        like: 60,
        price: 330000,
        price2: 660000,
        price3: 1550000, 
        optionTitle: "10회권",
        optionTitle02: "1달권",
        optionTitle03: "3개월권",
        detailURL1: "./img/school_img1.jpg",
        detailURL2: "./img/school_img2.jpg",
        detailURL3: "./img/school_img3.jpg",
        company: "펀딩회사 스타멍멍"
      },
      {
        id: 3,
        title: "펀딩 진행중",
        imgURL: "./img/Mschoolphoto3.jpg",
        name: "부평 코코유치원",
        funding: "0/20 명",
        personnel: "20명",
        like: 45,
        price: 330000,
        price2: 660000,
        price3: 1550000, 
        optionTitle: "10회권",
        optionTitle02: "1달권",
        optionTitle03: "3개월권",
        detailURL1: "./img/school_img1.jpg",
        detailURL2: "./img/school_img2.jpg",
        detailURL3: "./img/school_img3.jpg",
        company: "코코컴퍼니"
      },
      {
        id: 4,
        title: "펀딩 진행중",
        imgURL: "./img/Mschoolphoto4.jpg",
        name: "잠실 야옹유치원",
        funding: "0/20 명",
        personnel: "20명",
        like: 13,
        price: 330000,
        price2: 660000,
        price3: 1550000, 
        optionTitle: "10회권",
        optionTitle02: "1달권",
        optionTitle03: "3개월권",
        detailURL1: "./img/school_img1.jpg",
        detailURL2: "./img/school_img2.jpg",
        detailURL3: "./img/school_img3.jpg",
        company: "못말리는 집사들"
      },
    ];
    export default schoolMockup;